spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://postgres:5432/customer
    username: 'postgres'
    password: 'password'
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: rabbit-mq:5672

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
