spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: 'postgres'
    password: 'password'
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key