spring:
  application:
    name: eureka-server

server:
  port: 8761

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
